# Clean Up our Intake Data

In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt

from util import (
    np_age, np_concat, np_age_concat, get_lat, get_lng, 
    update_profession)

In [2]:
# Utility for displaying our DataFrames
from IPython.display import display_html
def display_side_by_side(*args):
    html_str=''
    for df in args:
        html_str+=df.to_html()
    display_html(html_str.replace('table','table style="display:inline"'),raw=True)

### First let us read in our unclean export data

In [3]:
unclean = pd.read_csv('../match-data/manual-match/export.csv')
unclean.replace([''], '---')
unclean.replace(['---'], '')

unclean

,number,formid,form.id.city,form.id.interview_date,form.int.has_job,form.int.has_other_income,form.int.months_unemployed,form.cd.first_name,form.cd.last_name,form.cd.mobile_num,...,form.jp.oppgen1,form.rw.rwage,form.ed.highest_edu_level,form.int.nation,form.id.gps,form.jp.will_work_qiz,form.jp.will_train_unpaid,form.jp.days_willing_train_unpaid,completed_time,received_on
0,0,uuid:232d8d82-0c11-4aa2-8a76-b4a244f60ca6,3,---,---,---,---,---,---,---,...,1,220,---,2,32.56341362 35.82743754 527.0 13.65,---,---,---,2018-04-19 08:38:55,2018-04-19 11:04:28
1,1,uuid:032b493f-e90e-42d8-ba55-66da02b70ec4,3,---,---,---,---,---,---,---,...,1,350,---,2,32.56381511 35.82414651 538.0 106.18,---,---,---,2018-04-19 09:43:50,2018-04-19 11:01:51
2,2,uuid:04b3cb22-7f12-4d7b-ad89-25f65b0dcdbe,3,---,---,---,---,---,---,---,...,1,300,---,2,32.57277106 35.80145862 587.0 25.78,---,---,---,2018-04-23 10:25:48,2018-04-23 10:25:57
3,3,uuid:326c85f5-ed1d-40fa-a370-17b43c2b0ea9,3,---,---,---,---,---,---,---,...,0,200,---,2,32.57245561 35.80178963 512.0 13.65,---,---,---,2018-04-23 08:43:45,2018-04-23 11:16:22
4,4,uuid:bdc35371-ba9d-4d1d-a678-3a1744c32297,3,---,---,---,---,---,---,---,...,0,300,---,2,32.53877962 35.84859773 637.0 16.68,---,---,---,2018-04-24 07:58:51,2018-04-24 07:58:56
5,5,uuid:74f432df-c4b6-4af3-94c2-48cdb0a68fa4,3,---,---,---,---,---,---,---,...,1,300,---,2,32.55391673 35.80441486 569.0 25.78,---,---,---,2018-04-24 10:16:34,2018-04-24 11:09:36
6,6,uuid:644eb4c7-b08b-4511-ab94-f3a949fb3e2a,3,---,---,---,---,---,---,---,...,0,300,---,2,NaN,---,---,---,2018-04-24 10:15:03,2018-04-24 11:06:39
7,7,uuid:129638e4-bce9-41b7-a933-779a595fc428,3,---,---,---,---,---,---,---,...,1,250,---,2,32.5053713 35.8638544 0.0 20.0,---,---,---,2018-04-24 09:50:11,2018-04-24 09:50:19
8,8,uuid:c185457a-a199-4784-93db-d501d7282229,3,---,---,---,---,---,---,---,...,0,250,---,2,32.53869682 35.84859372 627.0 4.55,---,---,---,2018-04-24 09:16:05,2018-04-24 09:16:04
9,9,uuid:d4f974d1-a152-413f-ba0f-d90817fd1429,3,---,---,---,---,---,---,---,...,1,350,---,2,32.5065657 35.8884198 0.0 20.0,---,---,---,2018-04-25 10:48:30,2018-04-25 10:47:57
10,10,uuid:7bdfd9da-69bc-40dc-b636-af5d06f748d7,3,---,---,---,---,---,---,---,...,1,280,---,2,32.54181986 35.84972841 637.0 12.13,---,---,---,2018-04-25 08:32:35,2018-04-26 07:24:37
11,11,uuid:5b8d79a8-1603-499d-b418-5a2373057473,3,---,---,---,---,---,---,---,...,1,220,---,2,32.53754535 35.84853229 624.0 18.2,---,---,---,2018-04-25 09:58:33,2018-04-26 07:24:41
12,12,uuid:1895eaee-466d-4f91-8fdf-886572ae8c56,3,---,---,---,---,---,---,---,...,1,300,---,2,32.5511176 35.8545241 0.0 20.0,---,---,---,2018-04-26 11:12:09,2018-04-26 11:54:22
13,13,uuid:3a607417-03ed-476e-b79e-b45bc2284226,3,---,---,---,---,---,---,---,...,1,35,---,---,32.55678713321686 35.82570791244507 564.0 12.13,---,---,---,2018-04-18 10:32:33,2018-04-19 06:24:29
14,14,uuid:e6213ceb-f1cc-4892-a46c-e7b9bebbd950,3,---,---,---,---,---,---,---,...,1,300,---,2,32.56367977 35.82685793 517.0 12.13,---,---,---,2018-04-18 11:47:52,2018-04-19 06:24:31
15,15,uuid:2f295e2b-5f35-4386-9f82-a49588c1bb3a,3,---,---,---,---,---,---,---,...,1,200,---,2,32.55641623 35.8486622 593.0 4.55,---,---,---,2018-04-26 11:25:53,2018-04-29 06:40:36
16,16,uuid:ed10d606-52fd-4212-ad35-953f1f758ebb,3,---,---,---,---,---,---,---,...,1,300,---,2,32.5490471 35.8541255 0.0 86.65,---,---,---,2018-04-29 06:45:37,2018-04-29 06:45:02
17,17,uuid:f3e4e226-5962-48d6-be26-39ae8073a085,3,---,---,---,---,---,---,---,...,1,300,---,2,32.5450675 35.8736439 0.0 27.42,---,---,---,2018-05-02 09:50:41,2018-05-02 10:29:01
18,18,uuid:a2bab9ed-2420-47dc-ad7a-6ca1d567b976,3,---,---,---,---,---,---,---,...,1,280,---,2,32.55807432 35.84583706 598.0 13.65,---,---,---,2018-04-30 07:53:59,2018-04-30 10:36:21
19,19,uuid:29c1c223-efa2-43e5-b4f8-20d30b3b6bc2,3,---,---,---,---,---,---,---,...,1,350,---,2,32.53706885 35.8492259 626.0 21.23,---,---,---,2018-05-03 08:44:40,2018-05-03 10:07:11
20,20,uuid:fd5514ef-26b9-4cfa-b1aa-a4637ea9fdb5,3,---,---,---,---,---,---,---,...,1,300,---,2,32.53581927 35.84986593 630.0 16.68,---,---,---,2018-05-07 08:37:20,2018-05-08 05:42:08
21,21,uuid:747f2451-483f-466c-b484-b04f771dd3d4,3,---,---,---,---,---,---,---,...,1,250,---,2,32.5246152 35.8530907 0.0 21.88,---,---,---,2018-05-08 08:40:03,2018-05-08 09:47:12
22,22,uuid:02ddf712-b7ff-45c9-a6c3-bf631217127c,3,---,---,---,---,---,---,---,...,1,200,---,2,32.52653241 35.83704535 682.0 13.65,---,---,---,2018-05-02 09:53:49,2018-05-02 11:26:16
23,23,uuid:31c9fe6b-59d6-4ba8-a6e4-206cd3b0651c,3,---,---,---,---,---,---,---,...,1,400,---,2,32.5783018 35.7281962 0.0 20.0,---,---,---,2018-05-02 10:37:55,2018-05-02 10:37:17
24,24,uuid:6746b426-ee36-45d5-8c38-e0555a0c5732,3,---,---,---,---,---,---,---,...,1,250,---,2,32.52656936645508 35.83694636821747 679.0 63.71,---,---,---,2018-05-02 08:41:46,2018-05-02 10:50:52
25,25,uuid:70ca3575-8537-449c-b64c-ec429c41b80a,3,---,---,---,---,---,---,---,...,1,300,---,2,32.5368351 35.8495418 0.0 22.52,---,---,---,2018-05-03 08:18:23,2018-05-03 09:16:57
26,26,uuid:0f71c390-edd4-4228-9a89-dd1feacf31a1,3,---,---,---,---,---,---,---,...,1,400,---,2,32.5225589 35.8510447 0.0 20.0,---,---,---,2018-05-09 09:30:04,2018-05-09 11:24:21
27,27,uuid:5dbd6caf-5c20-4cfe-b5ce-9546cc892ec3,3,---,---,---,---,---,---,---,...,0,400,---,2,32.5225589 35.8510447 0.0 20.9,---,---,---,2018-05-09 09:05:36,2018-05-09 09:05:43
28,28,uuid:7dcba8dc-aae3-4900-acd4-0b165cb5ccf9,3,---,---,---,---,---,---,---,...,1,400,---,2,32.55065447 35.83952829 606.0 13.65,---,---,---,2018-05-09 09:12:35,2018-05-09 12:37:34
29,29,uuid:8789c68f-b81c-4589-9cbd-fbd978b3f4b2,3,---,---,---,---,---,---,---,...,1,300,---,2,32.53599153 35.84990096 624.0 28.82,---,---,---,2018-05-10 09:26:40,2018-05-10 10:43:03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,970,eeb7ff12-02c7-47cd-bfe0-497745d6dab9,irbid,2018-07-23,0,0,1,أحمد,عيسى محمد حسين,789490028,...,---,---,primary,---,NaN,1,0,---,2018-07-23 06:40:28,2018-07-23 06:40:30
971,971,49f0cac6-8f20-4d9d-bb56-c47ece8cfa64,irbid,2018-07-23,0,0,2,علاء ياسر صلاح,الحايك,795579323,...,---,---,other,---,32.5449493 35.8563895 613.7 20.98,1,1,6,2018-07-23 08:20:23,2018-07-23 08:20:25
972,972,64e4ca88-12d5-4107-90bb-acaaccc8e548,amman,2018-07-22,0,0,1,جهاد يوسف,الحريري,787551632,...,---,---,primary,---,NaN,1,1,7,2018-07-24 18:32:11,2018-07-24 18:32:12
973,973,6cc1cd1f-0e0e-4b3f-9787-7caa637bdf85,amman,2018-07-24,0,0,2,عمر عطاالله,الحريري,798411374,...,---,---,primary,---,NaN,1,1,7,2018-07-24 18:36:47,2018-07-24 18:36:47
974,974,afebd4b4-b150-4731-84b3-1dcebb3db1ea,amman,2018-07-23,0,0,6,ربيع ابراهيم,خليل,792072621,...,---,---,college,---,NaN,1,1,30,2018-07-24 18:35:16,2018-07-24 18:35:17
975,975,61716a49-6ab8-4c92-9a16-225acd3e6057,amman,2018-07-24,0,0,2,خالد,سالم الزوكاني,790844679,...,---,---,secondary,---,NaN,1,1,5,2018-07-24 09:12:35,2018-07-24 09:12:37
976,976,30be27b4-8bcd-4ed3-9827-39914ffadedb,irbid,2018-07-24,0,0,36,خالد,محمد شفيق التميمي,772246349,...,---,---,primary,---,NaN,1,1,7,2018-07-24 09:58:57,2018-07-24 09:58:59
977,977,28f24a9d-0c62-4952-8200-b007d633a6a1,amman,2018-07-24,0,1,12,اسيل,سلامة الشوبكي,772715243,...,---,---,secondary,---,NaN,1,1,10,2018-07-24 09:39:32,2018-07-24 09:39:52
978,978,00eda3cb-745e-4be6-8813-a4f0d196de9e,irbid,2018-07-16,0,0,6,قاسم,أحمد الزيتاوي,790373299,...,---,---,primary,---,32.5211438 35.8550505 0.0 156.9,1,1,20,2018-07-16 08:52:00,2018-07-16 08:52:03
979,979,ed9f863e-3854-4325-8dad-f30b797a8f3c,irbid,2018-07-16,0,0,4,عنود,الشناق,780484432,...,---,---,secondary,---,32.57669058 35.79953975 502.0 95.57,0,1,30,2018-07-16 08:25:24,2018-07-16 10:33:35
980,980,a9590d48-25d1-42ab-acbb-ff8be3eed786,amman,2018-07-05,0,0,7,بدري علي,النصر,790613811,...,---,---,primary,---,NaN,---,---,---,2018-07-15 20:59:05,2018-07-16 06:05:03
981,981,565b4e2a-afe0-4fab-b50d-766033958c5d,amman,2018-06-25,0,0,6,هلال شرف,ابوسليم,789681084,...,---,---,secondary,---,NaN,---,---,---,2018-07-15 21:58:27,2018-07-16 06:13:53
982,982,f39951c5-fa58-4b7e-88ab-6e4e30c41e79,amman,2018-06-28,0,0,2,يوسف محمد,سعد,798508166,...,---,---,secondary,---,NaN,---,---,---,2018-07-15 21:57:47,2018-07-16 06:13:12
983,983,deedc3a2-ee41-4df6-a67a-afc9b6d2d102,irbid,2018-07-31,0,0,0,فلسطين,حسن,788662247,...,---,---,secondary,---,32.60695876 35.63021657 -129.0 66.73,0,1,7,2018-07-31 07:53:09,2018-07-31 09:25:13
984,984,9c8238eb-7df8-4dd6-aa30-4afad43c445e,irbid,2018-08-01,0,0,3,امل خليل,زعل,790613079,...,---,---,diploma,---,NaN,1,1,30,2018-08-01 11:31:02,2018-08-02 06:53:20
985,985,34b3f7ac-6024-44c0-8d6b-5ac284480b48,irbid,2018-08-02,0,0,1,ابراهيم احمد عبداللطيف,حسن,797007883,...,---,---,secondary,---,32.5449209 35.8563828 613.59 20.36,0,0,---,2018-08-02 07:41:09,2018-08-02 07:41:11
986,986,a997a5a9-96a1-4c37-bf82-541063200b80,irbid,2018-08-01,0,0,0,ساره,العنانبه,780351633,...,---,---,secondary,---,32.49559148 35.88073136 628.0 16.68,0,0,---,2018-08-01 08:46:42,2018-08-02 06:09:25
987,987,bf0ac9f9-bbf6-44ad-8187-9e030436caf8,irbid,2018-08-02,0,0,24,اسامه,برغوث,796434753,...,---,---,primary,---,32.54553362 35.85638824 618.0 25.78,1,1,3,2018-08-02 07:57:07,2018-08-02 07:57:09
988,988,4499ed83-3554-458b-bcdc-016c138db1c9,irbid,2018-08-01,0,0,1,عمر,حسين,789320287,...,---,---,bachelors,---,32.5448219 35.8563308 613.59 20.79,1,1,2,2018-08-01 09:44:34,2018-08-01 09:44:34
989,989,9ad179ec-09f2-4d1f-87b2-539ba3d200d1,irbid,2018-08-02,0,0,1,سوسن ياسر,الحسين,796459250,...,---,---,bachelors,---,32.544904 35.8563868 613.59 19.67,0,0,---,2018-08-02 10:09:00,2018-08-02 10:09:02
990,990,cdf2a1c1-7c5b-4220-8f4d-e61f16146568,irbid,2018-08-02,1,0,---,فائدة عبدالرحمن,قاسم,785539201,...,---,---,secondary,---,NaN,1,1,14,2018-08-02 10:24:09,2018-08-02 10:24:09
991,991,f7712abd-3e3e-45fe-9dae-d2a4f64c486e,irbid,2018-08-02,0,0,1,سوسن ياسر,الحسين,796459250,...,---,---,bachelors,---,32.5449198 35.8563999 613.59 19.78,0,0,---,2018-08-02 10:22:10,2018-08-02 10:22:11
992,992,c2d5e7db-0dc7-45a8-8bb2-cc6cdebd5bd3,irbid,2018-08-02,0,0,3,رماح كامل,جبور,787883626,...,---,---,secondary,---,NaN,0,0,---,2018-08-02 07:41:25,2018-08-02 11:07:59
993,993,ffbe2119-c62b-4b73-bfd3-d9fc981e13c9,irbid,2018-08-01,0,0,1,حسين مدالله,ابو زيد,798808418,...,---,---,primary,---,32.544921 35.8563855 613.59 20.3,1,0,---,2018-08-02 11:32:48,2018-08-02 11:32:49
994,994,9f3bafea-80ed-48fa-bcfb-875acccc4818,irbid,2018-08-01,0,0,3,شكري باسم,طلب,786604300,...,---,---,bachelors,---,32.5449184 35.8563913 613.59 19.98,1,1,0,2018-08-01 08:52:43,2018-08-01 08:52:46
995,995,675b694e-e54d-4824-9d0a-d1c04da700ac,irbid,2018-08-05,0,0,1,امينه,محمود,786360226,...,---,---,secondary,---,32.54409145 35.85721893 455.0 63.71,1,0,---,2018-08-05 05:47:56,2018-08-05 05:47:56
996,996,a4b26936-64aa-4401-8902-41500138a464,irbid,2018-08-05,0,0,4,رويده,الرفاعي,790809581,...,---,---,other,---,32.5447633 35.8562911 613.59 19.78,0,0,---,2018-08-05 06:00:03,2018-08-05 06:00:01
997,997,168d1c62-cf42-4272-afeb-964e539f1e7c,irbid,2018-08-05,0,0,0,هشام يوسف,غزاي,790214748,...,---,---,diploma,---,32.5552883 35.798939 0.0 164.4,1,1,30,2018-08-05 09:37:53,2018-08-05 09:37:56
998,998,35dd3c36-45c3-47a1-ad62-4c56fa6c45fa,amman,2018-08-05,0,0,NaN,خديجة,عبدالمعين هلال,789606934,...,---,---,secondary,---,31.87397619 36.0056033 876.0 21.23,1,0,---,2018-08-05 10:44:22,2018-08-05 10:44:24
999,999,420372ec-3af7-435b-a4c3-fa7dd4d00d76,irbid,2018-08-05,1,0,---,خالد,حسن حسن,798365530,...,---,---,college,---,32.544916 35.8563853 613.59 20.26,1,1,30,2018-08-05 12:20:35,2018-08-05 12:20:36

In [4]:
def map_cities(col):
    col = col.replace(['1'], 'mafraq')
    col = col.replace(['2'], 'amman')
    col = col.replace(['3'], 'irbid')
    col = col.replace(['4'], 'zarqa')
    return col

### Now we will merge, reformat columns and create a new "clean" data frame

In [5]:
clean = pd.DataFrame()

# Clean Nationality
unclean['form.int.nation'] = unclean['form.int.nation'].replace(['1'],
                                                                'jordanian')
unclean['form.int.nation'] = unclean['form.int.nation'].replace(['2'],
                                                                'syrian')
unclean['form.int.nation'] = unclean['form.int.nation'].replace(['---'], '')

unclean['form.int.nationality'] = unclean['form.int.nationality'].replace(
    ['---'], '')
unclean['nationalty'] = unclean['form.int.nationality'].map(
    str) + unclean['form.int.nation']
clean['nationality'] = unclean['nationalty'].replace([''], 'unknown')

# Clean Gender
unclean['form.dem.male'] = unclean['form.dem.male'].replace(['0'], 'female')
unclean['form.dem.male'] = unclean['form.dem.male'].replace(['1'], 'male')
unclean['form.dem.male'] = unclean['form.dem.male'].replace(['---'], '')
unclean['form.dem.gender'] = unclean['form.dem.gender'].replace(['---'], '')
clean[
    'gender'] = unclean['form.dem.gender'].map(str) + unclean['form.dem.male']

# Clean Education Level
unclean['form.ed.edu1'] = unclean['form.ed.edu1'].replace(['1'], 'none')
unclean['form.ed.edu1'] = unclean['form.ed.edu1'].replace(['2'], 'primary')
unclean['form.ed.edu1'] = unclean['form.ed.edu1'].replace(['3'], 'secondary')
unclean['form.ed.edu1'] = unclean['form.ed.edu1'].replace(['4'], 'college')
unclean['form.ed.edu1'] = unclean['form.ed.edu1'].replace(['5'], 'diploma')
unclean['form.ed.edu1'] = unclean['form.ed.edu1'].replace(['6'], 'bachelors')
unclean['form.ed.edu1'] = unclean['form.ed.edu1'].replace(['7'], 'masters')
unclean['form.ed.edu1'] = unclean['form.ed.edu1'].replace(['7'], 'doctorate')
unclean['form.ed.edu1'] = unclean['form.ed.edu1'].replace(['---'], '')
unclean['form.ed.highest_edu_level'] = unclean[
    'form.ed.highest_edu_level'].replace(['---'], '')
unclean['edu'] = unclean['form.ed.edu1'].map(
    str) + unclean['form.ed.highest_edu_level']
clean['education'] = unclean['edu'].replace([''], 'unknown')

# Clean Age
unclean['form.dem.age'] = unclean['form.dem.age'].replace(['---'], '')
unclean['form.dem.age_calc'] = unclean['form.dem.age_calc'].replace(['---'],
                                                                    '')
unclean['dob_age'] = np_age(unclean['form.dem.dob'])

unclean['age_concat'] = np_age_concat(unclean['form.dem.age'],
                                      unclean['form.dem.age_calc'])
clean['age'] = np_age_concat(unclean['age_concat'], unclean['dob_age'])

# Clean Night Shfit
unclean['form.jp.night'] = unclean['form.jp.night'].replace(['---'], '')
unclean['form.jp.will_work_night_shift'] = unclean[
    'form.jp.will_work_night_shift'].replace(['---'], '')
clean['night-shift'] = np_concat(unclean['form.jp.night'],
                                 unclean['form.jp.will_work_night_shift'])

unclean['form.cd.first_name'] = unclean['form.cd.first_name'].replace(['---'],
                                                                      '')
unclean['form.cd.fname'] = unclean['form.cd.fname'].replace(['---'], '')
unclean['form.cd.last_name'] = unclean['form.cd.last_name'].replace(['---'],
                                                                    '')
unclean['form.cd.lname'] = unclean['form.cd.lname'].replace(['---'], '')

clean['first-name'] = np_concat(unclean['form.cd.first_name'],
                                unclean['form.cd.fname'])
clean['last-name'] = np_concat(unclean['form.cd.last_name'],
                               unclean['form.cd.lname'])

# Job
unclean['form.int.has_job'] = unclean['form.int.has_job'].replace(['---'], '')
unclean['form.int.job'] = unclean['form.int.job'].replace(['---'], '')
clean['has_job'] = np_concat(unclean['form.int.has_job'], unclean['form.int.job'])

unclean['form.int.has_other_income'] = unclean[
    'form.int.has_other_income'].replace(['---'], '')
unclean['form.int.entrep'] = unclean['form.int.entrep'].replace(['---'], '')
clean['has_other_income'] = np_concat(unclean['form.int.has_other_income'], unclean['form.int.entrep'])

unclean['form.cd.mobile_num'] = unclean['form.cd.mobile_num'].replace(['---'],'')
unclean['form.cd.mob'] = unclean['form.cd.mob'].replace(['---'], '')
clean['mobile_number'] = np_concat(unclean['form.cd.mobile_num'], unclean['form.cd.mob'])

unclean['form.dem.marital_status'] = unclean[
    'form.dem.marital_status'].replace(['---'], '')
unclean['form.dem.marr'] = unclean['form.dem.marr'].replace(['---'], '')

unclean['form.dem.marr'] = unclean['form.dem.marr'].replace(['1'], 'married')
unclean['form.dem.marr'] = unclean['form.dem.marr'].replace(['2'], 'single')
unclean['form.dem.marr'] = unclean['form.dem.marr'].replace(['3'], 'divoriced')
unclean['form.dem.marr'] = unclean['form.dem.marr'].replace(['4'], 'widowed')
clean['marital_status'] = np_concat(unclean['form.dem.marital_status'], unclean['form.dem.marr'])

unclean['form.dem.num_children'] = unclean['form.dem.num_children'].replace(
    ['---'], '')
unclean['form.dem.child'] = unclean['form.dem.child'].replace(['---'], '')
clean['num_children'] = np_concat(unclean['form.dem.num_children'], unclean['form.dem.child'])

unclean['form.tn.num_training_courses'] = unclean[
    'form.tn.num_training_courses'].replace(['---'], '')
unclean['form.tn.tn3'] = unclean['form.tn.tn3'].replace(['---'], '')
clean['num_training_courses'] = np_concat(unclean['form.tn.num_training_courses'],
                                          unclean['form.tn.tn3'])

unclean['form.jp.will_live_in_dorm'] = unclean[
    'form.jp.will_live_in_dorm'].replace(['---'], '')
unclean['form.jp.dorm'] = unclean['form.jp.dorm'].replace(['---'], '')
clean['will_live_in_dorm'] = np_concat(unclean['form.jp.will_live_in_dorm'],
                                       unclean['form.jp.dorm'])

unclean['form.jp.weekly_days_willing_to_work'] = unclean[
    'form.jp.weekly_days_willing_to_work'].replace(['---'], '')
unclean['form.jp.days'] = unclean['form.jp.days'].replace(['---'], '')
clean['weekly_days_willing_to_work'] = np_concat(unclean['form.jp.weekly_days_willing_to_work'],
                                                 unclean['form.jp.days'])

unclean['form.jp.daily_hours_willing_to_work'] = unclean[
    'form.jp.daily_hours_willing_to_work'].replace(['---'], '')
unclean['form.jp.hours'] = unclean['form.jp.hours'].replace(['---'], '')
clean['daily_hours_willing_to_work'] = np_concat(unclean['form.jp.daily_hours_willing_to_work'],
                                                 unclean['form.jp.hours'])

unclean['form.cj.workspace_preference_calc'] = unclean[
    'form.cj.workspace_preference_calc'].replace(['---'], '')
unclean['form.cj.cjsect'] = unclean['form.cj.cjsect'].replace(['---'], '')

unclean['form.cj.cjsect'] = unclean['form.cj.cjsect'].replace(['1'], 'office')
unclean['form.cj.cjsect'] = unclean['form.cj.cjsect'].replace(['2'], 'home')
unclean['form.cj.cjsect'] = unclean['form.cj.cjsect'].replace(['3'], 'souk')
unclean['form.cj.cjsect'] = unclean['form.cj.cjsect'].replace(['4'], 'farm')
unclean['form.cj.cjsect'] = unclean['form.cj.cjsect'].replace(['5'], 'factory')
unclean['form.cj.cjsect'] = unclean['form.cj.cjsect'].replace(['6'], 'mine')
unclean['form.cj.cjsect'] = unclean['form.cj.cjsect'].replace(['7'], 'construction_site')
unclean['form.cj.cjsect'] = unclean['form.cj.cjsect'].replace(['8'], 'garage')
unclean['form.cj.cjsect'] = unclean['form.cj.cjsect'].replace(['9'], 'transport')
unclean['form.cj.cjsect'] = unclean['form.cj.cjsect'].replace(['10'], 'religious_building')
unclean['form.cj.cjsect'] = unclean['form.cj.cjsect'].replace(['11'], 'hospital')
unclean['form.cj.cjsect'] = unclean['form.cj.cjsect'].replace(['12'], 'school')
unclean['form.cj.cjsect'] = unclean['form.cj.cjsect'].replace(['13'], 'hotel')
unclean['form.cj.cjsect'] = unclean['form.cj.cjsect'].replace(['14'], 'restaraunt')

clean['preferred_workspace'] = np_concat(unclean['form.cj.workspace_preference_calc'],
                                      unclean['form.cj.cjsect'])

unclean['form.we.years_exp'] = unclean['form.we.years_exp'].replace(['---'],
                                                                    '')
unclean['form.we.yexp'] = unclean['form.we.yexp'].replace(['---'], '')
clean['years_experience'] = np_concat(unclean['form.we.years_exp'], unclean['form.we.yexp'])

unclean['form.ex.comments'] = unclean['form.ex.comments'].replace(['---'], '')
unclean['form.com2'] = unclean['form.com2'].replace(['---'], '')
clean['comments'] = unclean['form.ex.comments']
clean['eso_comments'] = unclean['form.com2']

unclean['form.ed.comp'] = unclean['form.ed.comp'].replace(['---'], '')

unclean['form.ed.comp'] = unclean['form.ed.comp'].replace(['0'], 'none')
unclean['form.ed.comp'] = unclean['form.ed.comp'].replace(['1'], 'basic')
unclean['form.ed.comp'] = unclean['form.ed.comp'].replace(['2'], 'word_processing')
unclean['form.ed.comp'] = unclean['form.ed.comp'].replace(['3'], 'specialized')
unclean['form.ed.comp'] = unclean['form.ed.comp'].replace(['4'], 'programmer')

unclean['form.ed.computer_exprience'] = unclean[
    'form.ed.computer_exprience'].replace(['---'], '')
clean['computer_experience'] = np_concat(unclean['form.ed.comp'], 
                                           unclean['form.ed.computer_exprience'])

unclean['form.ed.eng'] = unclean['form.ed.eng'].replace(['---'], '')

unclean['form.ed.eng'] = unclean['form.ed.eng'].replace(['0'], 'not_literate')
unclean['form.ed.eng'] = unclean['form.ed.eng'].replace(['1'], 'few_phrases')
unclean['form.ed.eng'] = unclean['form.ed.eng'].replace(['2'], 'simple_phrases')
unclean['form.ed.eng'] = unclean['form.ed.eng'].replace(['3'], 'extended_conversation')
unclean['form.ed.eng'] = unclean['form.ed.eng'].replace(['4'], 'literate')

unclean['form.ed.english_proficiency'] = unclean[
    'form.ed.english_proficiency'].replace(['---'], '')
clean['english_proficiency'] = np_concat(unclean['form.ed.eng'],
                                         unclean['form.ed.english_proficiency'])

unclean['form.jp.opposite_gender_manager'] = unclean[
    'form.jp.opposite_gender_manager'].replace(['---'], '')
unclean['form.jp.oppgen'] = unclean['form.jp.oppgen'].replace(['---'], '')

unclean['form.jp.oppgen'] = unclean['form.jp.oppgen'].replace(['0'], 'will_refuse')
unclean['form.jp.oppgen'] = unclean['form.jp.oppgen'].replace(['1'], 'no_issue')

clean['opposite_gender_manager'] = np_concat(unclean['form.jp.opposite_gender_manager'],
                                             unclean['form.jp.oppgen'])

unclean['form.jp.opposite_gender_coworkers'] = unclean[
    'form.jp.opposite_gender_coworkers'].replace(['---'], '')
unclean['form.jp.oppgen1'] = unclean['form.jp.oppgen1'].replace(['---'], '')
unclean['form.jp.oppgen1'] = unclean['form.jp.oppgen1'].replace(['0'], 'will_refuse')
unclean['form.jp.oppgen1'] = unclean['form.jp.oppgen1'].replace(['1'], 'no_issue')
clean['opposite_gender_coworkers'] = np_concat(unclean['form.jp.opposite_gender_coworkers'],
                                             unclean['form.jp.oppgen1'])

unclean['form.rw.expected_wage'] = unclean['form.rw.expected_wage'].replace(
    ['---'], '')
unclean['form.rw.rwage'] = unclean['form.rw.rwage'].replace(['---'], '')
clean['expected_wage'] = np_concat(unclean['form.rw.expected_wage'], unclean['form.rw.rwage'])


# Job Preference

unclean['form.jp.jp2'] = unclean['form.jp.jp2'].replace(['---'], '')
unclean['form.jp.first_preference'] = unclean['form.jp.first_preference'].replace(['---'], '')
unclean['form.jp.jp2'] = update_profession(unclean['form.jp.jp2'])

clean['first_job_sector_preference'] = np_concat(unclean['form.jp.first_preference'], 
                                                 unclean['form.jp.jp2'])

# Second Preference
unclean['form.jp.jp3'] = unclean['form.jp.jp3'].replace(['---'], '')
unclean['form.jp.second_preference'] = unclean['form.jp.second_preference'].replace(['---'], '')

unclean['form.jp.jp3'] = update_profession(unclean['form.jp.jp3'])

clean['second_job_sector_preference'] = np_concat(unclean['form.jp.second_preference'], 
                                                  unclean['form.jp.jp3'])

unclean['form.ed.major'] = unclean['form.ed.major'].replace(['1'], 'engineering')
unclean['form.ed.major'] = unclean['form.ed.major'].replace(['2'], 'business_econ')
unclean['form.ed.major'] = unclean['form.ed.major'].replace(['3'], 'natural_science')
unclean['form.ed.major'] = unclean['form.ed.major'].replace(['4'], 'social_science')
unclean['form.ed.major'] = unclean['form.ed.major'].replace(['5'], 'medical')
unclean['form.ed.major'] = unclean['form.ed.major'].replace(['6'], 'agriculture')
unclean['form.ed.major'] = unclean['form.ed.major'].replace(['7'], 'education')
unclean['form.ed.major'] = unclean['form.ed.major'].replace(['8'], 'automotive')
unclean['form.ed.major'] = unclean['form.ed.major'].replace(['9'], 'electrical')
unclean['form.ed.major'] = unclean['form.ed.major'].replace(['10'], 'construction')
unclean['form.ed.major'] = unclean['form.ed.major'].replace(['11'], 'it')
unclean['form.ed.major'] = unclean['form.ed.major'].replace(['12'], 'manufacturing')
unclean['form.ed.major'] = unclean['form.ed.major'].replace(['13'], 'architecture')
unclean['form.ed.major'] = unclean['form.ed.major'].replace(['14'], 'carpentry')
unclean['form.ed.major'] = unclean['form.ed.major'].replace(['15'], 'textile')

unclean['form.we.jdesc'] = update_profession(unclean['form.we.jdesc'])
unclean['form.we.jdesc'] = unclean['form.we.jdesc'].replace(['---'], '')
unclean['form.we.job_description'] = unclean['form.we.job_description'].replace(['---'], '')
clean['best_job_field'] = np_concat(unclean['form.we.jdesc'], unclean['form.we.job_description'])

unclean['form.we.jname'] = unclean['form.we.jname'].replace(['---'], '')
unclean['form.we.job_name'] = unclean['form.we.job_name'].replace(['---'], '')
clean['best_job_name'] = np_concat(unclean['form.we.jname'], unclean['form.we.job_name'])

unclean['form.cd.mob1'] = unclean['form.cd.mob1'].replace(['---'], '')
unclean['form.cd.sec_contact_mobile'] = unclean['form.cd.sec_contact_mobile'].replace(['---'], '')
clean['secondary_contact_mobile'] = np_concat(unclean['form.cd.mob1'], unclean['form.cd.sec_contact_mobile'])

unclean['form.id.eso_id'] = unclean['form.id.eso_id'].replace(['---'], '')
unclean['form.id.eid'] = unclean['form.id.eid'].replace(['---'], '')
clean['eso_id'] = np_concat(unclean['form.id.eid'], unclean['form.id.eso_id'])

unclean['form.id.date'] = unclean['form.id.date'].replace(['---'], '')
unclean['form.id.interview_date'] = unclean['form.id.interview_date'].replace(['---'], '')
clean['interview_date'] = np_concat(unclean['form.id.interview_date'], unclean['form.id.date'])

clean['national_id'] = unclean['form.cd.national_id']
clean['moi_id'] = unclean['form.cd.moi']
clean['unhcr_id'] = unclean['form.cd.unhcr_id']

clean['will_work_qiz'] = unclean['form.jp.will_work_qiz']
clean['will_train_unpaid'] = unclean['form.jp.will_train_unpaid']
clean['days_willing_to_train_unpaid'] = unclean['form.jp.days_willing_train_unpaid']

# unclean['form.id.city'] = unclean['form.id.city'].replace(['---'], '')
clean['city'] = map_cities(unclean['form.id.city'])

In [6]:
clean.to_csv('../match-data/manual-match/manual_clean_english.csv')

## Translate all English keywords to Arabic

In [7]:
translation = pd.read_csv('../match-data/translations/manual-match-translations-finished.csv')
translated_columns = pd.read_csv('../match-data/translations/manual-match-column-headers-translated.csv')
for index, row in translation.iterrows():
    clean = clean.replace([row['ID']], row['Arabic Translation'])
    

def translate_column(column):
    new_column = translated_columns.loc[translated_columns['ID'] == column]['Arabic Translation']
    return new_column.values[0]
    
    
clean.rename(columns=translate_column , inplace=True)
    
clean

,الجنسية,الجنس,المستوى التعليمي,العمر,قابلية العمل نوبات ليلية,الأسم الأول,الأسم الأخير,وجود وظيفة حالياً,وجود دخل آخر حالياً,رقم الهاتف الجوال,...,رقم الهاتف المحمول الثانوي,رقم مسؤول خدمات التوظيف,موعد المقابلة,الرقم الوطني,رقم وزارة الداخلية,رقم المفوضية,إذا عرضت عليك وظيفة في شركة تقع في منطقة صناعية مؤهلة مثل منطقة الحسن الصناعية ، هل ستكون على استعداد لقبول هذه الوظيفة؟,إذا عرضت عليك وظيفة طلبت منك حضور تدريب غير مدفوع قبل بدء العمل، فهل ستكون على استعداد لقبول هذه الوظيفة؟,كم من الوقت (بالأيام) ستكون على استعداد على القيام ابلتدريب الغير المدفوع؟,المدينة
0,لاجئ سوري,أنثى,ثانوي,48.0,0,امل,حامد قناطرة,0,0,795216977,...,790526977,1,2018-04-19,---,1.008447e+09,---,---,---,---,اربد
1,لاجئ سوري,ذكر,ثانوي,0.0,1,محمد,قناطره,0,0,795538618,...,798811732,1,2018-04-19,---,1.004443e+09,---,---,---,---,اربد
2,لاجئ سوري,ذكر,ابتدائي,44.0,1,محمد,ابو شناق,0,0,790332061,...,779660713,4,2018-04-23,---,1.002912e+09,---,---,---,---,اربد
3,لاجئ سوري,أنثى,ثانوي,28.0,0,رنا,اللبني,0,0,775998904,...,796596354,1,2018-04-23,---,8.001417e+09,---,---,---,---,اربد
4,لاجئ سوري,أنثى,دبلوم (غير فني),40.0,0,عفاف,العواد,0,0,795457213,...,795954919,4,2018-04-24,---,8.001188e+09,---,---,---,---,اربد
5,لاجئ سوري,أنثى,ابتدائي,0.0,0,مريم,الجهماني,0,0,796684778,...,790236758,1,2018-04-24,---,8.003168e+09,---,---,---,---,اربد
6,لاجئ سوري,أنثى,لا شيء,53.0,0,عزيزة حسين,ابو حصيني,0,0,790695877,...,799589229,9,2018-04-24,---,8.003165e+09,---,---,---,---,اربد
7,لاجئ سوري,أنثى,ثانوي,20.0,0,ولاء,العاسمي,0,0,798972432,...,795761798,2,2018-04-24,---,8.001261e+09,---,---,---,---,اربد
8,لاجئ سوري,أنثى,ثانوي,19.0,0,ايات,طحينه,0,0,781826033,...,795457213,4,2018-04-24,---,8.001188e+09,---,---,---,---,اربد
9,لاجئ سوري,أنثى,بكالوريوس,25.0,0,هيام,القداح,0,0,798385382,...,797934883,2,2018-04-25,---,1.005174e+09,---,---,---,---,اربد
10,لاجئ سوري,ذكر,ثانوي,45.0,1,محمود,عياش,0,0,798538794,...,790964653,1,2018-04-25,---,8.001356e+09,---,---,---,---,اربد
11,لاجئ سوري,أنثى,ثانوي,18.0,0,رانيا,سلامات,0,0,798813465,...,796841023,1,2018-04-25,---,8.001416e+09,---,---,---,---,اربد
12,لاجئ سوري,أنثى,ثانوي,44.0,0,فايزه عبدالحليم,البدوي,0,0,790311201,...,795575327,9,2018-04-26,---,8.001402e+09,---,---,---,---,اربد
13,unknown,ذكر,ابتدائي,0.0,0,محمد,قنبر,,,785546116,...,790240705,1,2018-04-18,---,8.004196e+09,---,---,---,---,اربد
14,لاجئ سوري,ذكر,ابتدائي,0.0,1,خالد,القناطرة,1,1,799719683,...,795199523,6,2018-04-18,---,1.004389e+09,---,---,---,---,اربد
15,لاجئ سوري,أنثى,ابتدائي,27.0,1,عتاب,سلامه,0,0,797370850,...,795164895,1,2018-04-26,---,1.003869e+09,---,---,---,---,اربد
16,لاجئ سوري,أنثى,ثانوي,43.0,0,زينات صابر,عياش,0,0,797051635,...,796798225,2,2018-04-26,---,1.007833e+09,---,---,---,---,اربد
17,لاجئ سوري,أنثى,ابتدائي,38.0,0,اماني اسماعيل,مهاوش,0,0,790186182,...,798277143,9,2018-05-02,---,8.001370e+09,---,---,---,---,اربد
18,لاجئ سوري,أنثى,ثانوي,42.0,1,سمر,الزعبي,0,0,797589744,...,791591253,1,2018-04-30,---,8.001522e+09,---,---,---,---,اربد
19,لاجئ سوري,ذكر,ابتدائي,33.0,1,محمود,الرفاعي,0,0,798277143,...,790186182,4,2018-05-03,---,8.001374e+09,---,---,---,---,اربد
20,لاجئ سوري,أنثى,ثانوي,34.0,0,رانيا,الحاج علي,0,0,797924032,...,796924901,4,2018-05-07,---,8.001146e+09,---,---,---,---,اربد
21,لاجئ سوري,ذكر,بكالوريوس,24.0,1,خالد عبدالناصر,محاميد,0,0,789570559,...,792819113,9,2018-05-08,---,1.005157e+09,---,---,---,---,اربد
22,لاجئ سوري,أنثى,ثانوي,45.0,0,سميره,طحينه,0,0,798492528,...,798128695,3,2018-05-02,---,1.005430e+09,---,---,---,---,اربد
23,لاجئ سوري,ذكر,ثانوي,27.0,1,علي ياسين,قديسات,1,0,790269676,...,792703813,2,2018-04-30,---,8.001872e+09,---,---,---,---,اربد
24,لاجئ سوري,أنثى,دبلوم (غير فني),44.0,0,منال,طحينه,0,0,795977116,...,797472018,1,2018-05-02,---,8.001261e+09,---,---,---,---,اربد
25,لاجئ سوري,ذكر,ابتدائي,41.0,1,رائد,الرفاعي,0,0,798130402,...,790916486,9,2018-05-03,---,8.001372e+09,---,---,---,---,اربد
26,لاجئ سوري,أنثى,دبلوم (غير فني),36.0,0,هناء احمد,محمد,0,0,798556995,...,798404579,2,2018-05-09,---,1.005894e+09,---,---,---,---,اربد
27,لاجئ سوري,أنثى,ابتدائي,26.0,0,سماح علي,الربداوي,0,0,799280897,...,790280347,9,2018-05-09,---,8.001269e+09,---,---,---,---,اربد
28,لاجئ سوري,ذكر,ثانوي,22.0,1,يونس,الناصر,0,0,796551248,...,797642791,4,2018-05-09,---,8.001712e+09,---,---,---,---,اربد
29,لاجئ سوري,ذكر,بكالوريوس,59.0,1,فايز,بزازي,0,0,786301914,...,797513481,1,2018-05-10,---,8.001285e+09,---,---,---,---,اربد
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,أردني,ذكر,ابتدائي,24.0,0,أحمد,عيسى محمد حسين,0,0,789490028,...,787253686,6,2018-07-23,9941047394,NaN,NaN,1,0,---,اربد
971,لاجئ سوري,ذكر,other,22.0,1,علاء ياسر صلاح,الحايك,0,0,795579323,...,nan,7,2018-07-23,NaN,8.001268e+09,16513C21102,1,1,6,اربد
972,لاجئ سوري,ذكر,ابتدائي,45.0,1,جهاد يوسف,الحريري,0,0,787551632,...,795680815,10,2018-07-22,NaN,1.000597e+09,19913c21896,1,1,7,عمان
973,لاجئ سوري,ذكر,ابتدائي,33.0,0,عمر عطاالله,الحريري,0,0,798411374,...,799294212,10,2018-07-24,NaN,1.002937e+09,199133c0666,1,1,7,عمان
974,أردني,ذكر,كلية أو تعليم تقني,21.0,1,ربيع ابراهيم,خليل,0,0,792072621,...,798850700,10,2018-07-23,9961053773,NaN,NaN,1,1,30,عمان
975,لاجئ سوري,ذكر,ثانوي,27.0,1,خالد,سالم الزوكاني,0,0,790844679,...,780064256,11,2018-07-24,NaN,1.003872e+09,19912c23863,1,1,5,عمان
976,أردني,ذكر,ابتدائي,49.0,1,خالد,محمد شفيق التميمي,0,0,772246349,...,nan,6,2018-07-24,9691019120,NaN,NaN,1,1,7,اربد
977,أردني,أنثى,ثانوي,23.0,0,اسيل,سلامة الشوبكي,0,1,772715243,...,775639189,11,2018-07-24,9942052235,NaN,NaN,1,1,10,عمان
978,لاجئ سوري,ذكر,ابتدائي,42.0,1,قاسم,أحمد الزيتاوي,0,0,790373299,...,796378557,6,2018-07-16,NaN,8.001371e+09,16513c13594,1,1,20,اربد
979,أردني,أنثى,ثانوي,22.0,1,عنود,الشناق,0,0,780484432,...,790959407,4,2018-07-16,9962071444,NaN,NaN,0,1,30,اربد
980,لاجئ سوري,ذكر,ابتدائي,55.0,0,بدري علي,النصر,0,0,790613811,...,789646679,10,2018-07-05,NaN,8.001359e+09,38813c64739,---,---,---,عمان
981,أردني,ذكر,ثانوي,23.0,0,هلال شرف,ابوسليم,0,0,789681084,...,777661616,10,2018-06-25,9941053249,NaN,NaN,---,---,---,عمان
982,أردني,ذكر,ثانوي,21.0,1,يوسف محمد,سعد,0,0,798508166,...,799057708,10,2018-06-28,9961002398,NaN,NaN,---,---,---,عمان
983,أردني,أنثى,ثانوي,36.0,0,فلسطين,حسن,0,0,788662247,...,780607258,1,2018-07-31,9822037180,NaN,NaN,0,1,7,اربد
984,لاجئ سوري,أنثى,دبلوم (غير فني),23.0,0,امل خليل,زعل,0,0,790613079,...,790235227,9,2018-08-01,NaN,8.001263e+09,16513c19336,1,1,30,اربد
985,أردني,ذكر,ثانوي,49.0,0,ابراهيم احمد عبداللطيف,حسن,0,0,797007883,...,796887365,7,2018-08-02,9681043881,NaN,NaN,0,0,---,اربد
986,أردني,أنثى,ثانوي,19.0,0,ساره,العنانبه,0,0,780351633,...,780727525,1,2018-08-01,9982067808,NaN,NaN,0,0,---,اربد
987,لاجئ سوري,ذكر,ابتدائي,18.0,0,اسامه,برغوث,0,0,796434753,...,796179885,1,2018-08-02,NaN,8.002733e+09,19913c30848,1,1,3,اربد
988,لاجئ سوري,ذكر,بكالوريوس,22.0,1,عمر,حسين,0,0,789320287,...,796717655,12,2018-08-01,NaN,1.005441e+09,16513C03083,1,1,2,اربد
989,لاجئ سوري,أنثى,بكالوريوس,21.0,0,سوسن ياسر,الحسين,0,0,796459250,...,nan,7,2018-08-02,NaN,NaN,NaN,0,0,---,اربد
990,أردني,أنثى,ثانوي,50.0,0,فائدة عبدالرحمن,قاسم,1,0,785539201,...,nan,9,2018-08-02,9682038965,NaN,NaN,1,1,14,اربد
991,لاجئ سوري,أنثى,بكالوريوس,21.0,0,سوسن ياسر,الحسين,0,0,796459250,...,798308552,7,2018-08-02,NaN,1.005457e+09,16513c06448,0,0,---,اربد
992,أردني,أنثى,ثانوي,26.0,0,رماح كامل,جبور,0,0,787883626,...,785603467,2,2018-08-02,9922038337,NaN,NaN,0,0,---,اربد
993,لاجئ سوري,ذكر,ابتدائي,49.0,0,حسين مدالله,ابو زيد,0,0,798808418,...,782009728,2,2018-08-01,NaN,8.001370e+09,19912c22935,1,0,---,اربد
994,لاجئ سوري,ذكر,بكالوريوس,26.0,1,شكري باسم,طلب,0,0,786604300,...,797310827,7,2018-08-01,NaN,1.003871e+09,84113C35002,1,1,0,اربد
995,أردني,أنثى,ثانوي,27.0,1,امينه,محمود,0,0,786360226,...,785435240,4,2018-08-05,9912033206,NaN,NaN,1,0,---,اربد
996,لاجئ سوري,أنثى,other,39.0,0,رويده,الرفاعي,0,0,790809581,...,792830413,1,2018-08-05,NaN,8.001322e+09,16513c08110,0,0,---,اربد
997,أردني,ذكر,دبلوم (غير فني),22.0,1,هشام يوسف,غزاي,0,0,790214748,...,796131375,2,2018-08-05,9951030425,NaN,NaN,1,1,30,اربد
998,لاجئ سوري,أنثى,ثانوي,28.0,0,خديجة,عبدالمعين هلال,0,0,789606934,...,781518574,15,2018-08-05,NaN,8.001569e+09,84113C06670,1,0,---,عمان
999,لاجئ سوري,ذكر,كلية أو تعليم تقني,32.0,1,خالد,حسن حسن,1,0,798365530,...,790094279,6,2018-08-05,NaN,1.005431e+09,16513c13745,1,1,30,اربد

### Lastly, lets save our cleaned data out as a csv

In [8]:
clean.to_csv('../match-data/manual-match/manual_clean_arabic.csv')