In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt

In [2]:
def concat(col1, col2, debug=False):
    prohibited = ['', '---', 'nan']
    if col1 not in prohibited:
        return col1
    elif col2 not in prohibited:
        return col2
    else:
        return ''

np_concat = np.vectorize(concat)

In [5]:
unclean = pd.read_csv('../match-data/firms-old.csv')
unclean.replace(['---'], '')

unclean['']

,number,formid,Instructions for ESO: Please complete this section before the interview with the respondent.,ESO ID,How was the firm identified?,Specify other.,"If identified through a referral (organizational partner or client), please write the name here.",Initial contact first name,Initial contact last name,Initial contact mobile phone number,...,"In making a decision to interview a job candidate, what characteristics are most important for your firm? Please select up to 6 from the list or provide us with other important characteristics. | other","In making a decision to interview a job candidate, what characteristics are most important for your firm? Please select up to 6 from the list or provide us with other important characteristics. | extra",Specify other.15,/Firm_Intake_03/vrpt_count,/Firm_Intake_03/locq_count,/Firm_Intake_03/meta/instanceID,completed_time,started_time,username,received_on
0,0,uuid:46e0d446-c875-409f-8300-af7e78a5f7bc,,3,9,,,حسين,جراروة,795468346,...,NaN,NaN,,0,0,uuid:46e0d446-c875-409f-8300-af7e78a5f7bc,2018-05-13 07:44:56,2018-05-10 10:54:27,eso03,2018-05-13 07:44:59
1,1,uuid:d816a845-46e3-4acf-a205-f0c4f99d5871,,8,9,,,دعاء,مقدادي,770271544,...,NaN,NaN,,4,1,uuid:d816a845-46e3-4acf-a205-f0c4f99d5871,2018-05-13 13:16:25,2018-05-10 08:49:34,eso08,2018-05-13 13:17:13
2,2,uuid:f57e5bb0-6e98-4df3-8857-a351d5324cd1,,8,9,,,فاخر,غرايبة,772292837,...,NaN,NaN,,0,2,uuid:f57e5bb0-6e98-4df3-8857-a351d5324cd1,2018-05-17 07:49:23,2018-05-16 08:10:07,eso08,2018-05-17 07:50:45
3,3,uuid:88f78fce-4485-488e-8f9e-bef6c2dc2dbb,,8,9,,,هديل,العمري,796270012,...,NaN,NaN,,2,2,uuid:88f78fce-4485-488e-8f9e-bef6c2dc2dbb,2018-05-22 08:05:04,2018-05-21 09:06:10,eso08,2018-05-22 08:05:09
4,4,uuid:5bae912a-24c3-408a-975c-e389d589bc0e,,8,9,,,ابراهيم,ذيابات,795461343,...,NaN,NaN,,0,1,uuid:5bae912a-24c3-408a-975c-e389d589bc0e,2018-05-17 07:30:55,2018-05-16 09:53:58,eso08,2018-05-17 07:50:30